### ISSUE TITLE
Course detail page

### ISSUE THREAD

**Issue by NoTimeInnovations** [NoTimeInnovations/notime-folio#13]
![WhatsApp Image 2024-09-23 at 00 03 21_9177e0e1](https://github.com/user-attachments/assets/5686d6b1-b3be-4c24-b08e-081ac379ea87)

### Course detail page
after enrolling 1st task can be this prerequisite

**Comment by Shatwik7** [comment]
![image](https://github.com/user-attachments/assets/08441e16-47a2-4c4e-b324-45b8eb5c0a63)
